---
services:
  mariadb:
    image: mariadb:11.3.2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=authelia
    networks:
      - authelianet
...
