---
services:
  authelia-backend:
    volumes:
      - './DuoPush/configuration.yml:/config/configuration.yml'
      - './DuoPush/users.yml:/config/users.yml'
      - './common/pki:/pki'
      - '/tmp:/tmp'
    user: ${USER_ID}:${GROUP_ID}
...
